// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbDjbiA9UBeI7d_qUwQb-PoNFF_EeKgus',
    appId: '1:620234085566:web:4d7dbd61d9d177f66c7aef',
    messagingSenderId: '620234085566',
    projectId: 'flutter-first-89aac',
    authDomain: 'flutter-first-89aac.firebaseapp.com',
    storageBucket: 'flutter-first-89aac.appspot.com',
    measurementId: 'G-WM8CR1X9BN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAQI_7cUwxhCvBikdg94XtA4a7Gw6cifQ',
    appId: '1:620234085566:android:d7abb09eb71758ee6c7aef',
    messagingSenderId: '620234085566',
    projectId: 'flutter-first-89aac',
    storageBucket: 'flutter-first-89aac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEkXZc4kRvIobunofaMKZFjoWcqQ_mI1g',
    appId: '1:620234085566:ios:574d775138aa9bfa6c7aef',
    messagingSenderId: '620234085566',
    projectId: 'flutter-first-89aac',
    storageBucket: 'flutter-first-89aac.appspot.com',
    iosClientId: '620234085566-ni2nqnmllh98qh8il97rsj8ru8rqiob2.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapppp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEkXZc4kRvIobunofaMKZFjoWcqQ_mI1g',
    appId: '1:620234085566:ios:574d775138aa9bfa6c7aef',
    messagingSenderId: '620234085566',
    projectId: 'flutter-first-89aac',
    storageBucket: 'flutter-first-89aac.appspot.com',
    iosClientId: '620234085566-ni2nqnmllh98qh8il97rsj8ru8rqiob2.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapppp',
  );
}
